### ISSUE TITLE
Providing default column value when not specified.

### ISSUE THREAD

**Issue by RickCarlino** [pyromaniac/mongoid_orderable#36]
Hi again,

I am getting duplicate column keys when I don't specify the column value on creation. Is this expected behavior?

```ruby
class Sequence
  embeds_many :steps
end

class Step
  include Mongoid::Document
  include Mongoid::Orderable

  embedded_in :sequence

  field :rank, type: Integer
  orderable scope: :sequence, column: :rank
end

seq = Sequence.create
Step.new(sequence: seq).save # Can't use create() in my use case
Step.new(sequence: seq).save
seq.steps.pluck(:rank)
# => [1, 1]
# Not unique ^
```

**Comment by pyromaniac** [comment]
Actually, we've got similar tests here: https://github.com/pyromaniac/mongoid_orderable/blob/master/spec/mongoid/orderable_spec.rb#L488-L516
But you are not using association accessor, maybe this is the cause, anyway looks like a bug, could you dive deeper please?

**Comment by RickCarlino** [comment]
Thanks for the quick response. I will take a look and let you know if I find anything.

**Comment by RickCarlino** [comment]
Ok- I found the solution for my use case:

**PROBLEM**: Embedded documents automatically infer the `orderable` `:scope`.

** SOLUTION**: Don't specify the `:scope` on embedded documents.

**Comment by pyromaniac** [comment]
Nice, thanks!
